@JobTrackerApi_HostAddress = http://localhost:5043

GET {{JobTrackerApi_HostAddress}}/jobapplications/5
Accept: application/json

###
POST {{JobTrackerApi_HostAddress}}/auth/register
Content-Type: application/json

{
  "email":"live@live.dk","userName":"gegegegeg","password": "Karim1", "ConfirmPassword" : "Karim1"
}

