@JobTrackerApi_HostAddress = https://localhost:7091

GET {{JobTrackerApi_HostAddress}}/jobapplications/
Accept: application/json
Authorization: Bearer 
###
POST {{JobTrackerApi_HostAddress}}/auth/register
Content-Type: application/json

{
  "email":"live@live.dk","userName":"gegegegeg","password": "Karim1", "ConfirmPassword" : "Karim1"
}

###
POST {{JobTrackerApi_HostAddress}}/auth/login
Content-Type: application/json

{
  "InputEmail":"live@live.dk","InputPassword": "Karim1"
}



